### ISSUE TITLE
Would prefer to have on maven central

### ISSUE THREAD

**Issue by levonk** [ankurcha/gcloud-logging-slf4j-logback#2]
Would it be possible to get this on maven central?

http://central.sonatype.org/pages/ossrh-guide.html

Thanks!

**Comment by ankurcha** [comment]
Thanks for the suggestion, i am following up on this!

**Comment by francisdb** [comment]
+1

**Comment by ankurcha** [comment]
Release to maven central done should be available in a few minutes / hour
