### ISSUE TITLE
Support logging of additional context fields

### ISSUE THREAD

**Issue by Laures** [ankurcha/gcloud-logging-slf4j-logback#6]
some libraries add fields to the log-contexts. currently there is no way to have such fields added to gcloud log messages. Usually these informations are part of the MDC (Mapped Diagnostic Context).

Example:

spring-sleuth adds a trace and span id to the log context (for tracing). having these fields in log messages is very useful to find all log messages that belong to a specific http request.

Solution:

add (filtered) MDC data to the json output (maybe the context field?)

see `ILoggingEvent.getMDCPropertyMap()`

https://github.com/logstash/logstash-logback-encoder/blob/ae1e3d91137d69b327f9977f096c145fbc893004/src/main/java/net/logstash/logback/composite/loggingevent/MdcJsonProvider.java

**Comment by Laures** [comment]
as an addition: stackdriver trace provides a "logs" link for traces that leads to a filtered logging view. The filter looks like this: 

`timestamp>="2017-08-04T10:50:37.233000Z" timestamp<="2017-08-04T10:50:57.284000Z" (trace="projects/<project_name>/traces/0000000000000000e012a24ac2d6d6c0" OR labels."appengine.googleapis.com/trace_id"="0000000000000000e012a24ac2d6d6c0")`

while that clearly is a very specific use-case for a log-library setting the trace-id in a way that fulfills this filter would be very useful

**Comment by ankurcha** [comment]
`v1.1.7` has trace support. MDC in a multithreaded environment is pretty fickle. I am happy to take PRs or suggestions on how to do that right.

**Comment by ankurcha** [comment]
#7 adds support for mdc fields whch should cover this
